--- name:default
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - true
  - true
  - true
  angular:
  - true
  - true
  - true
# If true, the component will send a zero command before getting into an
# exception state. Otherwise, it will not do anything
keep_position_on_exception: true

# The domain of what we are converting (true:position or false:velocity or
# efforts)
position_control: true
# This property defines the timeout for the cascade input port in seconds. 0
# means that the timeout would be ignored.
timeout_cascade: 1.0
# This property defines the timeout for the cmd_in input port in seconds. 0
# means that the timeout would be ignored.
timeout_in: 1.0
--- name:nothing
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - false
  angular:
  - false
  - false
  - false
--- name:no_xy
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - true
  - true
  - true
--- name:no_xyz
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - false
  angular:
  - true
  - true
  - true
--- name:only_z
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - false
  - false
--- name:only_yaw
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - false
  angular:
  - false
  - false
  - true
--- name:only_z_yaw
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - false
  - true
--- name:only_z_yaw_pitch
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - true
  - true

--- name:only_z_yaw_pitch_roll
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - true
  - true
  - true

--- name:only_z_pitch
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - true
  - false
--- name:only_xyz
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - true 
  - true 
  - true
  angular:
  - false
  - false
  - false
