--- name:default
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - true
  - true
  - true
  angular:
  - true
  - true
  - true
# If true, the component will send a zero command before getting into an
# exception state. Otherwise, it will not do anything
keep_position_on_exception: true

# This property defines the timeout for the cascade input port in seconds. 0
# means that the timeout would be ignored.
timeout_cascade: 1.0
# This property defines the timeout for the cmd_in input port in seconds. 0
# means that the timeout would be ignored.
timeout_in: 1.0
# The command frame (true:world or false:aligned)
world_frame: false

variance_threshold: .inf

--- name:nothing
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - false
  angular:
  - false
  - false
  - false

--- name:no_xy
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - true
  - true
  - true

--- name:only_z
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - false
  - false
--- name:only_z_yaw
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - false
  - true
--- name:only_yaw
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - false
  angular:
  - false
  - false
  - true
--- name:only_yaw_pitch
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - false
  angular:
  - false
  - true
  - true
--- name:only_z_yaw_pitch
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - true
  - true

--- name:only_z_yaw_pitch_roll
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - true
  - true
  - true

--- name:no_roll
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - true
  - true
  - true
  angular:
  - false
  - true
  - true

--- name:only_z_pitch
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - false
  - true
  - false

--- name:only_xyz
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - true
  - true
  - true
  angular:
  - false
  - false
  - false

--- name:position_parallel
# The command domain (true:position or false:velocity)
position_control: true
# Use the Ideal (false) or Parallel PID-Settings 
use_parallel_pid_settings: true
# Settings for the PID controllers
parallel_pid_settings:
  linear:
  - Ts: 0.01 #Not tested yet
    Kp: 0.1
    Ki: 0.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: -1.0
    YMin: -0.2
    YMax: 0.2
  - Ts: 0.01 #Not tested yet
    Kp: 0.1
    Ki: 0.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: -1.0
    YMin: -0.2
    YMax: 0.2
  - Ts: 0.01   
    Kp: 0.10       #0.5 #without Veloocity PID-Controller
    Ki: 0.0       #0.05 #without Veloocity PID-Controller
    Kd: 0.0       #0.5 #without Veloocity PID-Controller
    N: 0.0        #0.0 #without Veloocity PID-Controller
    B: 1.0        #1.0 #without Veloocity PID-Controller
    Tt: 1.0       #1.0 #without Veloocity PID-Controller
    YMin: -0.15    #-1.0 #without Veloocity PID-Controller
    YMax: 0.15     #1-0 #without Veloocity PID-Controller
  angular:
  - Ts: 0.01
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: -1.0
    YMin: -1.0
    YMax: 1.0
  - Ts: 0.01
    Kp: 0.2
    Ki: 0.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: 0.3
    YMin: -0.3
    YMax: 0.3
  - Ts: 0.01 #Not tested yet
    Kp: 1.0
    Ki: 0.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: -1.0
    YMin: -0.2
    YMax: 0.2

--- name:velocity_parallel
# The command domain (true:position or false:velocity)
position_control: false
# Use the Ideal (false) or Parallel PID-Settings 
use_parallel_pid_settings: true
# Settings for the PID controllers
parallel_pid_settings:
  linear:
  - Ts: 0.01 #Not tested yet
    Kp: 2.5
    Ki: 1.0
    Kd: 0.0
    N: 1.0
    B: 1.0
    Tt: 1.0
    YMin: -1.0
    YMax: 1.0
  - Ts: 0.01 #Not tested yet
    Kp: 2.5
    Ki: 1.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: 0.2
    YMin: -1.0
    YMax: 1.0
  - Ts: 0.01
    Kp: 10.0
    Ki: 5.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: 1.0
    YMin: -1.0
    YMax: 1.0
  angular:
  - Ts: 0.01 #Not tested yet
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: -1.0
    YMin: -1.0
    YMax: 1.0
  - Ts: 0.01 #Not tested yet
    Kp: 5.0
    Ki: 5.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: 1.0
    YMin: -1.0
    YMax: 1.0
  - Ts: 0.01
    Kp: 20.0
    Ki: 6.0
    Kd: 0.0
    N: 0.0
    B: 1.0
    Tt: 1.0
    YMin: -1.0
    YMax: 1.0

--- name:debug
# The command frame (true:world or false:aligned)
world_frame: true
